apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fadepls.fogatlas.fbk.eu
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: fogatlas.fbk.eu
  version: v1alpha1
  names:
    kind: FADepl
    plural: fadepls
  scope: Namespaced
  subresources:
    status: {}
  validation:
   openAPIV3Schema:
     type: object
     properties:
       apiVersion:
         type: string
       kind:
         type: string
       metadata:
         type: object
       spec:
         type: object
         properties:
           algorithm:
             type: string
             description: name of the scheduling algorithm to use
           externalendpoints:
             type: array
             items:
               type: string
               description: array of ids (uuid) of the external endpoints this application gets/sends data from/to
           microservices:
             type: array
             items:
               properties:
                 name:
                   type: string
                   description: name of a microservice composing the application
                 regions:
                   type: array
                   items:
                     properties:
                       regionrequired:
                         type: string
                         description: region id where the microservice should be placed
                       replicas:
                         type: integer
                         description: override, for this region, the replica value present in the deployment
                       image:
                         type: string
                         description: override, for this region, the image value present in the deployment
                 mipsrequired:
                   type: integer
                   description: amount of mips required by this microservice
                 deployment:
                   type: object
                   description: k8s appsv1.Deployment for the microservice
               allOf:
               - required: ["name"]
               - required: ["deployment"]
           dataflows:
             type: array
             items:
               properties:
                 bandwidthrequired:
                   type: integer
                   description: required bw (bps) for the data flow between sourceid and destinationid
                 latency:
                   type: integer
                   description: required latency (ms) for the data flow between sourceid and destinationid
                 sourceid:
                   type: string
                   description: microservice name source of this data flow
                 destinationid:
                   type: string
                   description: microservice name destination of this data flow
               allOf:
               - required: ["bandwidthrequired"]
               - required: ["latency"]
               - required: ["sourceid"]
               - required: ["destinationid"]
         allOf:
         - required: ["algorithm"]
         - required: ["externalendpoints"]
         - required: ["microservices"]
