apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fedfadepls.fogatlas.fbk.eu
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: fogatlas.fbk.eu
  version: v1alpha1
  names:
    kind: FedFADepl
    plural: fedfadepls
  scope: Namespaced
  validation:
   openAPIV3Schema:
     type: object
     properties:
        spec:
          type: object
          properties:
            name:
              type: string
              description: name of the fedfadepl (application)
            description:
              type: string
              description: description of the fedfadepl (application)
            algorithm:
              type: string
              description: name of the scheduling algorithm to use
            externalendpoints:
              type: array
              items:
                type: string
                description: array of ids (uuid) of the external endpoints this application gets/sends data from/to
            microservices:
              type: array
              properties:
                name:
                  type: string
                  description: name of one the microservice composing the application
                federateddeployment:
                  type: object
                  description: k8s types.kubefed.io/v1beta1/FederatedDeployment for this microservice
            dataflows:
              type: array
              properties:
                bandwidthrequired:
                  type: integer
                  description: required bw (bps) for the data flow between sourceid and destinationid
                bandwidthassigned:
                  type: integer
                  description: bw assigned (bps) for the data flow between sourceid and destinationid
                latencyrequired:
                  type: integer
                  description: required latency (ms) for the data flow between sourceid and destinationid
                sourceid:
                  type: string
                  description: microservice name source of this data flow
                destinationid:
                  type: string
                  description: microservice name destination of this data flow
